name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        

      # Docker 빌드 및 이미지 푸시
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Modify python version HERE

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dianalove/fastapi_git:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      # Docker Hub에서 이미지 내려받기 및 실행
      - name: Pull and run Docker image from Docker Hub
        run: |
          function stop_and_pull_run_image() {
            CONTAINER_ID=$(docker ps -q --filter ancestor=dianalove/fastapi_git:latest)
            if [ ! -z "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
            fi
            docker pull dianalove/fastapi_git:latest
            docker run -d -p 80:80 dianalove/fastapi_git:latest
          }
          stop_and_pull_run_image
